# Generated by Django 2.1 on 2018-09-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonname', models.CharField(max_length=32)),
                ('academicname', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=32)),
                ('bodycolor', models.CharField(max_length=64)),
                ('targetfood', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=2048)),
            ],
        ),
    ]
