# Generated by Django 2.0.8 on 2018-08-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDD_WEB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mongo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.TextField(max_length=50)),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('ip', models.TextField(max_length=50)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
