# Generated by Django 2.0.8 on 2018-08-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDD_WEB', '0002_mongo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='db_mongo',
        ),
    ]
