# Generated by Django 2.0.8 on 2018-08-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDD_WEB', '0005_auto_20180823_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVConn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(max_length=100)),
                ('document', models.FileField(upload_to='documents/csv/')),
                ('document_upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
