# Generated by Django 2.0.3 on 2018-08-27 06:57

import IDD_WEB.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDD_WEB', '0006_csvconn'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXCELConn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(max_length=100)),
                ('document', models.FileField(upload_to='documents/excel/', validators=[IDD_WEB.validators.validate_excel_extension])),
                ('document_upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JSONConn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(max_length=100)),
                ('document', models.FileField(upload_to='documents/json/', validators=[IDD_WEB.validators.validate_json_extension])),
                ('document_upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='csvconn',
            name='document',
            field=models.FileField(upload_to='documents/csv/', validators=[IDD_WEB.validators.validate_csv_extension]),
        ),
    ]
